import assert from "node:assert/strict";
import test from "node:test";

const accessToken=process.env.E2E_APP_ACCESS_TOKEN;
async function api(base,path,options={}){const response=await fetch(`${base}${path}`,{...options,headers:{accept:"application/json",...(options.headers??{})}});const body=await response.json();return {response,body};}
const cookies=(response)=>(response.headers.getSetCookie?.()??[]).map((value)=>value.split(";")[0]).join("; ");
async function auth(base){const login=await api(base,"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:accessToken})});const authCookie=cookies(login.response);const csrf=await api(base,"/api/security/csrf",{headers:{cookie:authCookie}});return {cookie:[authCookie,cookies(csrf.response)].join("; "),csrf:csrf.body.token};}
const sync=(base,session,headers={})=>api(base,"/api/x/sync",{method:"POST",headers:{cookie:session.cookie,"x-csrf-token":session.csrf,"content-type":"application/json","idempotency-key":crypto.randomUUID(),...headers},body:"{}"});

test("expired refreshable authorization is checked only after explicit sync",async()=>{const base=process.env.E2E_REFRESH_SUCCESS_URL;const session=await auth(base);const status=await api(base,"/api/x/status",{headers:{cookie:session.cookie}});assert.equal(status.body.authorization.state,"authorization_check_required");assert.equal(status.response.headers.get("x-openx-e2e-x-call-count"),"0");const result=await sync(base,session);assert.equal(result.response.status,200);assert.equal(result.response.headers.get("x-openx-e2e-x-call-count"),"4");assert.match(result.response.headers.get("x-openx-e2e-x-call-kinds")??"",/^token,identity,/);});

test("failed refresh becomes reconnect required and one reconnect action preserves cache",async()=>{const base=process.env.E2E_REFRESH_REJECT_URL;const session=await auth(base);const before=await api(base,"/api/x/sync",{headers:{cookie:session.cookie}});assert.equal(before.body.available,true);const failed=await sync(base,session,{"x-openx-e2e-token-status":"401"});assert.equal(failed.response.status,401);assert.equal(failed.body.error,"X_RECONNECT_REQUIRED");assert.equal(failed.response.headers.get("x-openx-e2e-x-call-count"),"1");const status=await api(base,"/api/x/status",{headers:{cookie:session.cookie}});assert.equal(status.body.authorization.state,"reconnect_required");const reconnect=await api(base,"/api/x/disconnect",{method:"POST",headers:{cookie:session.cookie,"x-csrf-token":session.csrf,"content-type":"application/json"},body:JSON.stringify({intent:"reconnect"})});assert.equal(reconnect.response.status,200);assert.equal(reconnect.body.retainedData,true);const after=await api(base,"/api/x/sync",{headers:{cookie:session.cookie}});assert.equal(after.body.available,true);assert.equal(after.body.data.syncedAt,before.body.data.syncedAt);});

test("expired authorization without refresh is reconnect required without provider contact and normal disconnect keeps durable records",async()=>{const base=process.env.E2E_NO_REFRESH_URL;const session=await auth(base);const status=await api(base,"/api/x/status",{headers:{cookie:session.cookie}});assert.equal(status.body.authorization.state,"reconnect_required");const attempt=await sync(base,session);assert.equal(attempt.response.status,401);assert.equal(attempt.response.headers.get("x-openx-e2e-x-call-count"),"0");const disconnect=await api(base,"/api/x/disconnect",{method:"POST",headers:{cookie:session.cookie,"x-csrf-token":session.csrf,"content-type":"application/json"},body:JSON.stringify({intent:"disconnect"})});assert.equal(disconnect.response.status,200);const cache=await api(base,"/api/x/sync",{headers:{cookie:session.cookie}});assert.equal(cache.body.available,false);const analytics=await api(base,"/api/analytics?range=7D",{headers:{cookie:session.cookie}});assert.ok(analytics.body.raw.postSnapshots.length>0);assert.ok(analytics.body.followers.series.length>0);});
