"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import "../globals.css";

export default function LoginPage() {
  const [token,setToken] = useState(""); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);const [schemaError,setSchemaError]=useState(false);
  useEffect(() => { void fetch("/api/x/status").then(async (response) => { if(response.status===503){const body=await response.json().catch(()=>({})) as {error?:string};if(body.error?.startsWith("LOCAL_DATABASE_"))setSchemaError(true);return}if (response.ok) { const status = await response.json() as {accessProtected?:boolean}; if (!status.accessProtected) window.location.href = "/"; } }); }, []);
  const submit = async (event:FormEvent) => { event.preventDefault(); setBusy(true); setError(""); const response = await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}); setBusy(false); if (response.ok) window.location.href="/"; else { const body=await response.json().catch(()=>({})) as {error?:string}; setError(body.error==="APP_ACCESS_TOKEN_REQUIRED"?"This configured instance is locked until its operator sets APP_ACCESS_TOKEN.":body.error==="TOO_MANY_ATTEMPTS"?"Too many attempts. Try again later.":"Invalid access token."); } };
  return <main className="login-page"><section><div className="step-icon"><LockKeyhole size={22}/></div><span className="eyebrow">PRIVATE INSTANCE</span>{schemaError?<div role="alert"><h1>Database setup required</h1><p>Apply the existing D1 migrations, restart OpenX, then try again.</p><code>npm run db:migrate:local</code><br/><code>npm run db:migrate:remote</code></div>:<><h1>Unlock OpenX Growth</h1><p>Enter the access token configured by the owner of this deployment.</p><form onSubmit={submit}><label>Access token<input type="password" value={token} onChange={(event)=>setToken(event.target.value)} autoComplete="current-password" required/></label>{error && <div className="inline-error" role="alert">{error}</div>}<button className="primary-btn" disabled={busy}>{busy ? "Checking…" : <>Continue <ArrowRight size={15}/></>}</button></form></>}<p className="login-privacy">By continuing, you acknowledge this instance&apos;s <a href="/privacy">privacy notice</a>. No credentials are sent to the project maintainers.</p></section></main>;
}
